spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/  #设置与Eureka Server交互的地址
---
spring:
  profiles: test
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/  #设置与Eureka Server交互的地址